/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Articulo;
import Controller.Lista;
import java.io.Serializable;

/**
 *
 * @author teodora
 */
public class UI extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        guardar.setVisible(false);
        Sobreescribir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        titulo = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        cuerpo = new javax.swing.JTextPane();
        editar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        Anterior = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();
        Sobreescribir = new javax.swing.JButton();
        Categoria = new javax.swing.JLabel();
        imgBack = new javax.swing.JPanel();
        tagCate = new javax.swing.JComboBox<>();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setIconImages(null);
        setResizable(false);

        background.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Revista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Mukti Narrow", 1, 14))); // NOI18N
        background.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N

        titulo.setEditable(false);
        titulo.setFont(new java.awt.Font("Mukti Narrow", 1, 12)); // NOI18N
        jScrollPane1.setViewportView(titulo);

        cuerpo.setEditable(false);
        cuerpo.setFont(new java.awt.Font("malayalam", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(cuerpo);

        editar.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        editar.setText("Editar");
        editar.setPreferredSize(new java.awt.Dimension(98, 37));
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        guardar.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        guardar.setText("Guardar");
        guardar.setPreferredSize(new java.awt.Dimension(98, 37));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        nuevo.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.setPreferredSize(new java.awt.Dimension(98, 37));
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        Anterior.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        Anterior.setText("Anterior");
        Anterior.setPreferredSize(new java.awt.Dimension(98, 37));
        Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorActionPerformed(evt);
            }
        });

        Siguiente.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        Siguiente.setText("Siguiente");
        Siguiente.setPreferredSize(new java.awt.Dimension(98, 37));
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        Sobreescribir.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        Sobreescribir.setText("Sobreescribir");
        Sobreescribir.setPreferredSize(new java.awt.Dimension(98, 37));
        Sobreescribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreescribirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sobreescribir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Siguiente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sobreescribir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        Categoria.setFont(new java.awt.Font("Mukti Narrow", 1, 14)); // NOI18N
        Categoria.setText("Categoria");

        imgBack.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        imgBack.setLayout(new java.awt.GridLayout(1, 1));

        tagCate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "politica", "tech", "deportes", "" }));
        tagCate.setSelectedIndex(3);
        tagCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagCateActionPerformed(evt);
            }
        });

        img.setFont(new java.awt.Font("Mukti Narrow", 1, 12)); // NOI18N
        img.setText(" ");
        img.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Autor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Mukti Narrow", 3, 14))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Categoria)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tagCate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imgBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgBack, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(Categoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tagCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        save();
        guardar.setVisible(false);
        System.out.println("Guardado");
        posicion++;


    }//GEN-LAST:event_guardarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        titulo.setEditable(true);
        cuerpo.setEditable(true);

        Sobreescribir.setVisible(true);
        background.revalidate();
        background.repaint();


    }//GEN-LAST:event_editarActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        limpiar();
        titulo.setEditable(true);
        cuerpo.setEditable(true);
        guardar.setVisible(true);
        img.setIcon(null);
        imgBack.revalidate();
        imgBack.repaint();

    }//GEN-LAST:event_nuevoActionPerformed

    private void tagCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagCateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tagCateActionPerformed

    
    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed

        dibujarSiguiente();
    }//GEN-LAST:event_SiguienteActionPerformed

    private void AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorActionPerformed

        dibujarAnterior();
    }//GEN-LAST:event_AnteriorActionPerformed

    private void SobreescribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreescribirActionPerformed
        sobreEscribir();
        Sobreescribir.setVisible(false);
    }//GEN-LAST:event_SobreescribirActionPerformed

    public void sobreEscribir() {
        Articulo actual = (Articulo) revista.elementoActual();
        Articulo nuevo = new Articulo(titulo.getText(), cuerpo.getText());
        revista.sustituir(actual, nuevo);
    }

    public void limpiar() {
        titulo.setText("");
        cuerpo.setText("");
        tagCate.setSelectedIndex(3);
    }
    
    /**
     
     */
    public void save() {

        Articulo nuevo = new Articulo(titulo.getText(), cuerpo.getText());
        titulo.setEditable(false);
        cuerpo.setEditable(false);
        revista.añadir(nuevo);
        background.revalidate();
        background.repaint();

        switch (tagCate.getSelectedIndex()) {

            case 0:
                img.setIcon(new javax.swing.ImageIcon(getClass().getResource(politica)));
                imgBack.revalidate();
                imgBack.repaint();
                nuevo.setRuta(politica);
                break;

            case 1:
                img.setIcon(new javax.swing.ImageIcon(getClass().getResource(tech)));
                imgBack.revalidate();
                imgBack.repaint();
                nuevo.setRuta(tech);
                break;

            case 2:
                img.setIcon(new javax.swing.ImageIcon(getClass().getResource(deportes)));
                imgBack.revalidate();
                imgBack.repaint();
                nuevo.setRuta(deportes);
                break;

            default:
                break;
        }

        System.out.println(nuevo.getCuerpo());

    }

    public void dibujarSiguiente() {
        revista.setSiguiente();
        Articulo siguiente = (Articulo) revista.elementoActual();
        titulo.setText(siguiente.getTitulo());
        cuerpo.setText(siguiente.getCuerpo());
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource(siguiente.getRuta())));
        imgBack.revalidate();
        imgBack.repaint();
        background.revalidate();
        background.repaint();

//        if (posicion > 0) {
//
//            Articulo siguiente = (Articulo) revista.localizarPosicion(posicion);
//
//            titulo.setText(siguiente.getTitulo());
//            cuerpo.setText(siguiente.getCuerpo());
//            img.setIcon(new javax.swing.ImageIcon(getClass().getResource(siguiente.getRuta())));
//            imgBack.revalidate();
//            imgBack.repaint();
//
//            background.revalidate();
//            background.repaint();
    }

    public void dibujarAnterior() throws NullPointerException {
        revista.setAnterior();
        Articulo anterior = (Articulo) revista.elementoActual();
        titulo.setText(anterior.getTitulo());
        cuerpo.setText(anterior.getCuerpo());
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource(anterior.getRuta())));
        imgBack.revalidate();
        imgBack.repaint();
        background.revalidate();
        background.repaint();

//        Articulo anterior = (Articulo) revista.localizarPosicion(posicion);
//
//        if (posicion > 0) {
//
//            if (anterior != null) {
//                titulo.setText(anterior.getTitulo());
//                cuerpo.setText(anterior.getCuerpo());
//                img.setIcon(new javax.swing.ImageIcon(getClass().getResource(anterior.getRuta())));
//                imgBack.revalidate();
//                imgBack.repaint();
//
//                background.revalidate();
//                background.repaint();
//
//                if (posicion < 0 || anterior == null) {
//                    System.out.println("Es el primero");
//                    anterior = (Articulo) revista.localizarPosicion(1);
//                    cuerpo.setText(anterior.getCuerpo());
//                    img.setIcon(new javax.swing.ImageIcon(getClass().getResource(anterior.getRuta())));
//                    imgBack.revalidate();
//                    imgBack.repaint();
//
//                    background.revalidate();
//                    background.repaint();
//                }
//            } else {
//                throw new NullPointerException("No se encontro el articulo o este es el primer articulo");
//            }
//        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    Lista revista = new Lista();
    Articulo predeterminado = new Articulo("", "");
    String politica = "/Resources/img03.png";
    String tech = "/Resources/img04.png";
    String deportes = "/Resources/img05.png";
    int posicion = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior;
    private javax.swing.JLabel Categoria;
    private javax.swing.JButton Siguiente;
    private javax.swing.JButton Sobreescribir;
    private javax.swing.JPanel background;
    private javax.swing.JTextPane cuerpo;
    private javax.swing.JButton editar;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel img;
    private javax.swing.JPanel imgBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nuevo;
    private javax.swing.JComboBox<String> tagCate;
    private javax.swing.JTextPane titulo;
    // End of variables declaration//GEN-END:variables
}
